name: DevSecOps Microservice Client

on:
  push:
    branches:
      - master

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.branch.name=master
            -Dsonar.projectKey=myorganizationjpjh_devsecops
            -Dsonar.organization=myorganizationjpjh
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops:${{ github.sha }} .
        working-directory: .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/devsecops:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devsecops:microserviceclient
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops:microserviceclient
